### ISSUE TITLE
Publish to npm!

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zap-cli#4]

**Comment by tgrecojs** [comment]
@shakeelmohamed I published this package to NPM where it is located [here](https://www.npmjs.com/package/zap-cli). I am working to make it so that it can be installed globally.

**Comment by shakeelmohamed** [comment]
Can you unpublish it? I intended to do this myself, which is why it didn't have the "up for grabs" label. I don't want it published without a proper readme and tests. Besides that, I want it published on my npm account.

**Comment by tgrecojs** [comment]
darn. i'm sorry

**Comment by tgrecojs** [comment]
@shakeelmohamed it is unpublished from the registry. sorry about that again! was just trying to help out :smirk:

**Comment by shakeelmohamed** [comment]
Thank you! Generally publishing anything is a big deal, and you should always ask the project maintainer before doing that. I will spend some more time on this since you've showed interest

**Comment by tgrecojs** [comment]
@shakeelmohamed not a problem. Again, my sincere apologies as I should have in fact informed you about this but I hope you do know that no malice was intended at all! I switched it back to private and I also pushed over my commit dealing with #6. 

And yeah let me know if I can help you out with anything. I could definitely work to set up some testing if you're interesting in me helping out with that, but let me know!

**Comment by shakeelmohamed** [comment]
We're good now :+1:

**Comment by v1rtl** [comment]
Any progress on publishing it?

if `zap-cli` is taken we can use `zap-cli-player` or `zap-player`

**Comment by shakeelmohamed** [comment]
@talentlessguy I actually forgot all about this! Just published as `zen-audio`, thanks for the reminder
