### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zap-cli#6]
In the README we need:
- [x] Usage information
- [x] Screenshots, maybe even a gif
- [x] License information
- [x] A link back to the main project
- [x] Add badges for Travis CI, repo stats & gitter

**Comment by tgrecojs** [comment]
@shakeelmohamed hey i came across this the other day and it's  definitely something i'd like to help with. I can record gifs very easily on my computer. 

I do think I am executing the script wrong though. I have to run `node index.js <YouTube URL | video ID | search query>` in order for it to work. I tried running zap and it said command now found. Here is a screenshot of what is going on.

<img width="588" alt="screenshot 2016-02-13 04 57 35" src="https://cloud.githubusercontent.com/assets/6646552/13027057/61d2bdf0-d20e-11e5-9af8-9c5081aaf5fd.png">

I think this maybe the reason why I have to run the tool in the way that I do. I was going to include a gif of that but didn't think it was necessary till i got this figured out. 

Let me know what you think.

**Comment by shakeelmohamed** [comment]
@thomasjosephgreco great! If you run `npm install -g .` within the project directory. Then you should be able to just run `zap https://www.youtube.com/watch?v=koJv-j1usoI`. If you don't want to install globally, you can run `node index.js https://www.youtube.com/watch?v=koJv-j1usoI`

We don't have any tests at the moment, so running `npm test` should yield the same result you saw.

**Comment by tgrecojs** [comment]
**completed tasks**
- [x] link to original repo
- [x] usage information
- [x] gif of how it's used

**still needed**
- [ ] license info
- [ ] add badges

@shakeelmohamed where can I find links to the badges? I've never used them before. Also, I am about to push over an updated readme.md now. I separated this branch from #4 although I initially was going to commit them together. This was good that I separated these, right? Ha, still getting used to all of this and I know people like their stuff a certain way. Anyways, let me know what you think of what I did.

**Comment by shakeelmohamed** [comment]
@thomasjosephgreco I left some comments on your PR. You can take the gitter badge directly from the [main repo's README](https://raw.githubusercontent.com/zen-audio-player/zen-audio-player.github.io/master/README.md), the Travis CI & GitHub stats links will need to be updated but can also be pulled from there.

For the license section, just add the following:

``` markdown
## License

zap-cli is licensed under the MIT license.
```

**Comment by shakeelmohamed** [comment]
Thanks for doing this @thomasjosephgreco
